import "./globals.css";
import { Metadata } from "next";


import { Providers } from "./providers";
import { Jost } from 'next/font/google';
import { SideBar } from '@/components/sideBar/SideBar';


const jostFont = Jost({
	variable: "--font-jost",
	subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
    <html lang="en" className="dark" style={{ colorScheme: " dark" }}>
      <body className={`${jostFont.variable} antialiased h-[100%]`}>
        <Providers>
          <div className="flex h-full w-full">
            <SideBar />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
